/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Equipo.Implementacion;

import java.awt.image.BufferedImage;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import Negocio.Equipo.TransferEquipo;
import Presentacion.equipo;
import Presentacion.Controlador.Controlador;

/**
 *
 * @author SERCAMA
 */
public class PresentacionEquipo extends javax.swing.JFrame {

    /**
     * Creates new form presEquipo
     */
    public PresentacionEquipo(Object equipo) {
        initComponents(equipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Object equipo) {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label10 = new JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        textFieldID = new java.awt.TextField();
        textFieldNombreEquipo = new java.awt.TextField();
        textFieldEquipacionPrinc = new java.awt.TextField();
        textFieldEquipacionSecun = new java.awt.TextField();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jComboBoxPais = new javax.swing.JComboBox();
        jComboBoxCiudad = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label1.setText("Nombre Equipo:");
        getContentPane().add(label1);
        label1.setBounds(23, 42, 94, 22);

        label2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label2.setText("Categoría:");
        getContentPane().add(label2);
        label2.setBounds(23, 74, 64, 22);

        label3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label3.setText("ID:");
        getContentPane().add(label3);
        label3.setBounds(23, 10, 25, 22);

        label4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label4.setText("Colores Equipaciones:");
        getContentPane().add(label4);
        label4.setBounds(23, 106, 125, 22);

        label5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label5.setText("- Equipación Principal:");
        getContentPane().add(label5);
        label5.setBounds(63, 138, 129, 22);

        label6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label6.setText("- Equipación Secundaria:");
        getContentPane().add(label6);
        label6.setBounds(63, 170, 146, 22);

        label7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label7.setText("País:");
        getContentPane().add(label7);
        label7.setBounds(23, 206, 31, 22);

        label8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        label8.setText("Ciudad:");
        getContentPane().add(label8);
        label8.setBounds(23, 242, 46, 22);

        label10.setBackground(new java.awt.Color(204, 204, 204));
        label10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(label10);
        label10.setBounds(381, 10, 136, 152);

        button1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button1.setLabel("Examinar...");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExaminarActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(396, 192, 111, 36);

        button2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button2.setLabel("Crear");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(258, 238, 113, 36);
        button2.getAccessibleContext().setAccessibleName("Button2");

        textFieldID.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textFieldID);
        textFieldID.setBounds(58, 10, 134, 22);

        textFieldNombreEquipo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textFieldNombreEquipo);
        textFieldNombreEquipo.setBounds(127, 42, 134, 22);

        textFieldEquipacionPrinc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textFieldEquipacionPrinc);
        textFieldEquipacionPrinc.setBounds(202, 138, 134, 22);

        textFieldEquipacionSecun.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textFieldEquipacionSecun);
        textFieldEquipacionSecun.setBounds(219, 170, 134, 22);

        button3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button3.setLabel("Actualizar");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(396, 238, 111, 36);
        button3.getAccessibleContext().setAccessibleDescription("");

        button4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button4.setLabel("Ver Equipo");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(button4);
        button4.setBounds(396, 329, 111, 35);

        button5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button5.setLabel("Eliminar");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(258, 284, 113, 35);

        button6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button6.setLabel("Ver Estadísticas");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(button6);
        button6.setBounds(258, 329, 113, 35);

        button7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        button7.setLabel("Ver Plantilla");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPlantillaActionPerformed(evt);
            }
        });
        getContentPane().add(button7);
        button7.setBounds(396, 284, 111, 35);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(23, 329, 112, 35);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCategoria);
        jComboBoxCategoria.setBounds(127, 74, 134, 20);

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ej", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxPais);
        jComboBoxPais.setBounds(79, 208, 130, 20);

        jComboBoxCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCiudad);
        jComboBoxCiudad.setBounds(79, 242, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/fondo_ball1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 400);
        
        if(equipo!=null){
        	textFieldID.setText(((TransferEquipo) equipo).getId()+"");
        	textFieldNombreEquipo.setText(((TransferEquipo) equipo).getNombre());
        	jComboBoxCategoria.setSelectedItem(((TransferEquipo) equipo).getCategoria());
        	textFieldEquipacionPrinc.setText(((TransferEquipo) equipo).getColorPrinc());
        	textFieldEquipacionSecun.setText(((TransferEquipo) equipo).getColorSecun());
        	jComboBoxCiudad.setSelectedItem(((TransferEquipo) equipo).getCiudad());
        	jComboBoxPais.setSelectedItem(((TransferEquipo) equipo).getPais());
        	f = ((TransferEquipo) equipo).getEscudo();
        	try
        	{
        		ImageIcon im=null;
        		BufferedImage buffer = ImageIO.read(f);
        		im = new ImageIcon(buffer);
        		label10.setIcon(im);
            }
        	catch( Exception exp){}
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    	JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY );
        int seleccion = jfc.showOpenDialog( this );
        if( seleccion == JFileChooser.APPROVE_OPTION )
        {
        	 f = jfc.getSelectedFile();
            try
            {
                 ImageIcon im=null;
                 BufferedImage buffer = ImageIO.read(f);
                 im = new ImageIcon(buffer);
                 //En el editor de texto colocamos su contenido
                label10.setIcon(im);
            }catch( Exception exp){}
       }
    }//GEN-LAST:event_button1ActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    	try{
    	    TransferEquipo trEquipo = new TransferEquipo(-1);
    	    trEquipo.setCategoria(jComboBoxCategoria.getSelectedItem()+"");
    	    trEquipo.setCiudad(jComboBoxCiudad.getSelectedItem()+""); 
    	    trEquipo.setNombre(textFieldNombreEquipo.getText()); 
    	    trEquipo.setPais(jComboBoxPais.getSelectedItem()+""); 
    	    trEquipo.setColorPrinc(textFieldEquipacionPrinc.getText());
    	    trEquipo.setColorSecund(textFieldEquipacionSecun.getText());
    	    trEquipo.setEscudo(f);
    	    setVisible(false);
    	    Controlador.getInstancia().accion(2, trEquipo);
    	}
    	catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Campo/s introducido/s erroneamente", "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_button3ActionPerformed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    	try{
    	    TransferEquipo trEquipo = new TransferEquipo(-1);
    	    trEquipo.setCategoria(jComboBoxCategoria.getSelectedItem()+"");
    	    trEquipo.setCiudad(jComboBoxCiudad.getSelectedItem()+""); 
    	    trEquipo.setNombre(textFieldNombreEquipo.getText()); 
    	    trEquipo.setPais(jComboBoxPais.getSelectedItem()+""); 
    	    trEquipo.setColorPrinc(textFieldEquipacionPrinc.getText());
    	    trEquipo.setColorSecund(textFieldEquipacionSecun.getText());
    	    trEquipo.setEscudo(f);
    	    setVisible(false);
    	    Controlador.getInstancia().accion(1, trEquipo);
    	}
    	catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Campo/s introducido/s erroneamente", "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_button2ActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    	setVisible(false);
    	new equipo().setVisible(true);
    }//GEN-LAST:event_button5ActionPerformed

    private void buttonVerPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void buttonVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void buttonVerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    	try{
    	    TransferEquipo trEquipo = new TransferEquipo(this.textFieldNombreEquipo.getText(),this.jComboBoxCategoria.getSelectedItem()+"");
    	    setVisible(false);
    	    Controlador.getInstancia().accion(3, trEquipo);
    	}
    	catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Campo/s introducido/s erroneamente", "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new presEquipo().setVisible(true);
            	PresentacionEquipo pe = new PresentacionEquipo(null);
                pe.setSize(565,430);
                pe.setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public File f;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxPais;
    private javax.swing.JComboBox jComboBoxCiudad;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private JLabel label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.TextField textFieldID;
    private java.awt.TextField textFieldNombreEquipo;
    private java.awt.TextField textFieldEquipacionPrinc;
    private java.awt.TextField textFieldEquipacionSecun;
    // End of variables declaration//GEN-END:variables
}
